title: Project
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              display: Title
              validate:
                - required
          -
            handle: ro_title
            field:
              type: text
              display: 'RO Title'
              width: 33
          -
            handle: it_title
            field:
              type: text
              display: 'IT Title'
              width: 33
          -
            handle: ru_title
            field:
              type: text
              display: 'RU Title'
              width: 33
          -
            handle: description
            field:
              type: textarea
              display: Description
          -
            handle: ro_description
            field:
              type: textarea
              display: 'RO Description'
              width: 33
          -
            handle: it_description
            field:
              type: textarea
              display: 'IT Description'
              width: 33
          -
            handle: ru_description
            field:
              type: text
              display: 'RU Description'
              width: 33
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
          -
            handle: link
            field:
              type: link
              display: Link
          -
            handle: image
            field:
              container: assets
              type: assets
              display: Image
          -
            handle: tags
            field:
              taxonomies:
                - skils
              type: terms
              display: Tags
