name: Deploy to DigitalOcean on Release

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DO_SSH_PRIVATE_KEY }}

      - name: Deploy to DigitalOcean server
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.DO_SERVER_IP }} << 'EOF'
            cd /var/www/cris-portfolio-be
            git pull origin main
            composer install --no-dev --optimize-autoloader
